[project]
name = "00-django-starter-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ttanvirr", email = "tanvir.artisan@gmail.com" }
]
requires-python = ">=3.15"
dependencies = [
    "django>=6.1",
]

[project.scripts]
00-django-starter-template = "00_django_starter_template:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
